Repository Igalia/meta-webkit, pull requests merged in 2025-03, with the labels that each got.

#538 dav1d: Fix CVE-2024-1580
  recipes-multimedia/dav1d/dav1d.inc
  recipes-multimedia/dav1d/dav1d/CVE-2024-1580.patch
Labels: is a backport

#539 dav1d: Fix CVE-2024-1580
  recipes-multimedia/dav1d/dav1d.inc
  recipes-multimedia/dav1d/dav1d/CVE-2024-1580.patch
Labels: is a backport

#540 dav1d: Fix CVE-2024-1580
  recipes-multimedia/dav1d/dav1d.inc
  recipes-multimedia/dav1d/dav1d/CVE-2024-1580.patch
Labels: is a backport

#541 Update README with additional layer dependencies
  README.md
Labels: enhancement, help-wanted

#542 wpe-testbed: Add recipe to the layer
  recipes-graphics/wpe-testbed_git.bb
Labels: enhancement
