Repository Igalia/meta-webkit, pull requests merged in 2025-02, with the labels that each got.

#530 ci: Add retry mechanism for fetching sources in bitbake-build
  .github/actions/bitbake-build/action.yml
Labels: enhancement

#533 ci: Enhance GitHub Actions for Bitbake Build and Repo
  .github/actions/bitbake-build/action.yml
  .github/actions/bitbake-repo/action.yml
  .github/workflows/test-build.yml
Labels: enhancement

#534 libwpe: Add recipe for release 1.16.2
  recipes-browser/libwpe/libwpe_1.16.2.bb
Labels: version-update, to be backported

#535 [backport] libwpe: Add recipe for release 1.16.2
  recipes-browser/libwpe/libwpe_1.16.2.bb
Labels: is a backport
